custom:
  bert_base_path: Model/Training/pretrained_models/chinese-roberta-wwm-ext-large
  cnhubert_base_path: Model/Training/pretrained_models/chinese-hubert-base
  device: cuda
  is_half: true
  t2s_weights_path: Model/Training/pretrained_models/gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt
  vits_weights_path: Model/Training/pretrained_models/s2G488k.pth
default:
  bert_base_path: Model/Training/pretrained_models/chinese-roberta-wwm-ext-large
  cnhubert_base_path: Model/Training/pretrained_models/chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: Model/Training/pretrained_models/gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt
  vits_weights_path: Model/Training/pretrained_models//s2G488k.pth